"use client";
import { IcoZap } from "@/components/icons";
import { SECTION_STYLE } from "@/data/constants";
import { scheduleLabel } from "@/data/helpers";

export default function EmailPreview({ output, report }) {
  const now = new Date().toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" });
  return (
    <div className="rounded-xl border border-slate-200 overflow-hidden shadow-sm bg-white">
      <div className="bg-[#FFCC00] px-5 py-3 flex items-center gap-2.5">
        <div className="w-6 h-6 rounded-full bg-white flex items-center justify-center flex-shrink-0">
          <IcoZap size={12} className="text-amber-700" />
        </div>
        <span className="text-[#1a1a1a] text-sm font-semibold">Agent Coach</span>
      </div>
      <div className="bg-slate-50 border-b border-slate-200 px-5 py-3 space-y-1.5 text-xs text-slate-500">
        <div className="flex gap-3"><span className="font-semibold w-12 text-slate-400">From</span><span>Agent Coach &lt;coach@agentcoach.ai&gt;</span></div>
        <div className="flex gap-3"><span className="font-semibold w-12 text-slate-400">To</span><span className="font-medium text-slate-700">{report.delivery.address}</span></div>
        <div className="flex gap-3"><span className="font-semibold w-12 text-slate-400">Subject</span><span className="font-medium text-slate-700">[{scheduleLabel(report.schedule).split(" \u00B7 ")[0]}] {output.title} — {now}</span></div>
      </div>
      <div className="px-5 py-4">
        <p className="text-xs text-slate-400 mb-3">{now} · Generated by Agent Coach · <span className="italic">"{report.prompt.slice(0, 60)}..."</span></p>
        <h3 className="text-base font-bold text-slate-900 mb-4">{output.title}</h3>
        <div className="space-y-4">
          {output.sections.map((sec) => {
            const s = SECTION_STYLE[sec.style] || SECTION_STYLE.neutral;
            return (
              <div key={sec.heading}>
                <div className="flex items-center gap-2 mb-2">
                  <div className={`w-2 h-2 rounded-full flex-shrink-0 ${s.dot}`} />
                  <p className={`text-xs font-bold uppercase tracking-wide ${s.heading}`}>{sec.heading}</p>
                </div>
                <ul className="space-y-1.5 pl-4">
                  {sec.items.map((item) => (
                    <li key={item} className="text-xs text-slate-700 leading-relaxed flex gap-2">
                      <span className="text-slate-300 flex-shrink-0">—</span>
                      <span>{item}</span>
                    </li>
                  ))}
                </ul>
              </div>
            );
          })}
        </div>
        <div className="mt-5 pt-4 border-t border-slate-100 flex items-center gap-2 text-xs text-slate-400">
          <IcoZap size={11} className="text-[#FFCC00]" />
          Generated by Agent Coach · Payments Platform · {scheduleLabel(report.schedule)} ·
          <span className="text-amber-600 ml-0.5">Manage schedules</span>
        </div>
      </div>
    </div>
  );
}
